create table if not exists public.movements (
  id integer generated by default as identity primary key,
  user_id text not null,
  type text not null check (type in ('Gasto', 'Ingreso', 'Transferencia')),
  amount double precision not null check (amount > 0),
  description text not null,
  merchant text,
  category text not null,
  subcategory text,
  payment_method text not null,
  account_id integer,
  destination_account_id integer,
  card_id integer,
  installments integer not null default 1 check (installments between 1 and 60),
  scope text not null default 'Personal',
  status text not null default 'Confirmado',
  source text not null default 'Manual',
  movement_date text not null,
  exclude_budget boolean not null default false,
  reviewed boolean not null default true,
  tags text not null default '[]',
  attachment_count integer not null default 0,
  created_at text not null,
  updated_at text
);

create table if not exists public.accounts (
  id integer generated by default as identity primary key,
  user_id text not null,
  name text not null,
  type text not null,
  balance double precision not null default 0,
  institution text not null default '',
  color text not null default '#6757dd',
  active boolean not null default true,
  created_at text not null,
  updated_at text
);

create table if not exists public.credit_cards (
  id integer generated by default as identity primary key,
  user_id text not null,
  name text not null,
  bank text not null,
  last4 text not null check (last4 ~ '^[0-9]{4}$'),
  credit_limit double precision not null check (credit_limit > 0),
  used double precision not null default 0,
  closing_day integer not null check (closing_day between 1 and 31),
  due_day integer not null check (due_day between 1 and 31),
  next_payment double precision not null default 0,
  color text not null default '#20273a',
  active boolean not null default true,
  created_at text not null,
  updated_at text
);

create table if not exists public.budgets (
  id integer generated by default as identity primary key,
  user_id text not null,
  name text not null,
  category text not null,
  limit_amount double precision not null check (limit_amount > 0),
  month text not null,
  active boolean not null default true,
  created_at text not null,
  updated_at text
);

create table if not exists public.commitments (
  id integer generated by default as identity primary key,
  user_id text not null,
  name text not null,
  kind text not null,
  amount double precision not null check (amount > 0),
  outstanding double precision,
  due_date text not null,
  status text not null default 'Pendiente',
  installments integer,
  paid_installments integer not null default 0,
  movement_id integer,
  card_id integer,
  category text not null default 'Otros',
  created_at text not null,
  updated_at text
);

create table if not exists public.goals (
  id integer generated by default as identity primary key,
  user_id text not null,
  name text not null,
  target double precision not null check (target > 0),
  saved double precision not null default 0,
  target_date text not null,
  color text not null default '#6757dd',
  created_at text not null,
  updated_at text
);

create table if not exists public.recurring (
  id integer generated by default as identity primary key,
  user_id text not null,
  name text not null,
  type text not null,
  amount double precision not null check (amount > 0),
  frequency text not null,
  next_date text not null,
  account text not null,
  category text not null,
  active boolean not null default true,
  created_at text not null,
  updated_at text
);

create table if not exists public.rules (
  id integer generated by default as identity primary key,
  user_id text not null,
  contains text not null,
  category text not null,
  subcategory text not null default '',
  active boolean not null default true,
  created_at text not null,
  updated_at text
);

create table if not exists public.attachments (
  id integer generated by default as identity primary key,
  user_id text not null,
  movement_id integer,
  storage_key text not null,
  file_name text not null,
  content_type text not null,
  size integer not null,
  created_at text not null
);

create table if not exists public.preferences (
  user_id text primary key,
  currency text not null default 'PEN',
  date_format text not null default 'DD/MM/YYYY',
  theme text not null default 'system',
  security_cushion double precision not null default 400,
  dashboard_preferences text not null default '{}',
  notifications text not null default '{}',
  updated_at text not null
);

create table if not exists public.gmail_connections (
  user_id text primary key,
  email text not null default '',
  encrypted_refresh_token text not null,
  history_id text,
  status text not null default 'connected',
  last_sync_at text,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.ingestion_events (
  id integer generated by default as identity primary key,
  user_id text not null,
  provider text not null,
  external_id text not null,
  fingerprint text not null,
  status text not null,
  raw_subject text not null default '',
  error text,
  movement_id integer,
  created_at text not null,
  updated_at text not null
);

create index if not exists idx_movements_user_date on public.movements (user_id, movement_date);
create index if not exists idx_movements_user_type on public.movements (user_id, type);
create index if not exists idx_movements_user_status on public.movements (user_id, status);
create index if not exists idx_accounts_user on public.accounts (user_id);
create index if not exists idx_credit_cards_user on public.credit_cards (user_id);
create index if not exists idx_budgets_user_month on public.budgets (user_id, month);
create index if not exists idx_commitments_user_due on public.commitments (user_id, due_date);
create index if not exists idx_goals_user on public.goals (user_id);
create index if not exists idx_recurring_user_next on public.recurring (user_id, next_date);
create index if not exists idx_rules_user on public.rules (user_id);
create index if not exists idx_attachments_user_movement on public.attachments (user_id, movement_id);
create unique index if not exists idx_ingestion_provider_external on public.ingestion_events (user_id, provider, external_id);
create unique index if not exists idx_ingestion_fingerprint on public.ingestion_events (user_id, fingerprint);

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'movements', 'accounts', 'credit_cards', 'budgets', 'commitments',
    'goals', 'recurring', 'rules', 'attachments', 'preferences',
    'gmail_connections', 'ingestion_events'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists owner_select on public.%I', table_name);
    execute format('drop policy if exists owner_insert on public.%I', table_name);
    execute format('drop policy if exists owner_update on public.%I', table_name);
    execute format('drop policy if exists owner_delete on public.%I', table_name);
    execute format('create policy owner_select on public.%I for select to authenticated using ((select auth.uid())::text = user_id)', table_name);
    execute format('create policy owner_insert on public.%I for insert to authenticated with check ((select auth.uid())::text = user_id)', table_name);
    execute format('create policy owner_update on public.%I for update to authenticated using ((select auth.uid())::text = user_id) with check ((select auth.uid())::text = user_id)', table_name);
    execute format('create policy owner_delete on public.%I for delete to authenticated using ((select auth.uid())::text = user_id)', table_name);
  end loop;
end $$;

